# Generated by Django 4.2.19 on 2025-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="参会人员姓名")),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="会议室名称"),
                ),
                ("area", models.CharField(max_length=50, verbose_name="区域")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可预订"),
                            ("maintenance", "维护中"),
                            ("busy", "忙碌"),
                        ],
                        default="available",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
            ],
        ),
    ]
